# Generated by Django 3.2.13 on 2023-10-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField()),
                ('video', models.CharField(default='Пусто', max_length=256)),
                ('image', models.ImageField(upload_to='main_images')),
                ('raiting', models.FloatField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('director', models.CharField(default='Пусто', max_length=128)),
                ('category', models.ForeignKey(default='Фильмы', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category')),
                ('genre', models.ForeignKey(default='Боевик', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
