# Generated by Django 3.2.13 on 2023-10-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_film_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
